export const POKEMON_TYPE = {
  grass: "grass",
  fire: "fire",
  water: "water",
  bug: "bug",
  normal: "normal",
  poison: "poison",
  electric: "electric",
  ground: "ground",
  fairy: "fairy",
  fighting: "fighting",
  psychic: "psychic",
  ghost: "ghost",
  dragon: "dragon",
  ice: "ice",
};
export const POKEMON_COLOR = {
  grass: "#70CDB1",
  fire: "#E9756F",
  water: "#8ABCF5",
  bug: "#CAC098",
  normal: "#E3E6D2",
  poison: "#CDA2DF",
  electric: "#F5DA82",
  ground: "#C4882E",
  fairy: "#E4C3E5",
  fighting: "#9A999A",
  psychic: "#C0C007",
  ghost: "#3E3B34",
  dragon: "#ECAD1B",
  ice: "#C8E4EA",
};
